<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Index</RootNamespace>
    <AssemblyName>Index.Windows</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Index.Core\Index.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.19" />
    <PackageReference Include="RapidOcrNet" Version="4.1.0" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="OcrModels\v4\*.*" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Index" />
    <InternalsVisibleTo Include="Index.Tests" />
  </ItemGroup>

</Project>
